name: deploy

on:
  push:
    branches:
      - main
      - feature/push_images_to_ecr

env:
  AWS_REGION: ap-northeast-1

jobs:
  deploy:
    name: Deploy app to AWS Fargate
    runs-on: ubuntu-latest

  steps:
    - name: Configure aws credentials for prod
#      if: github.ref == 'refs/heads/main'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}

        aws-region: ${{ env.AWS_REGION }}
